In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
import statsmodels as sm

In [2]:
schools_data = pd.read_csv('./input/school_data.csv', encoding='ISO-8859–1')

In [3]:
schools_data.columns = ['school_id', 'agency_id', 'operating_agency_name', 'school_name', 'city_name', 'state', 'latitude', 'longitude', 'metro_centric_locale', 'urban_centric_locale', 'school_status_code']

In [4]:
schools_data

,school_id,agency_id,operating_agency_name,school_name,city_name,state,latitude,longitude,metro_centric_locale,urban_centric_locale,school_status_code
0,10000200277,100002,ALABAMA YOUTH SERVICES,SEQUOYAH SCHOOL - CHALKVILLE CAMPUS,PINSON,AL,33.674697,-86.627775,3,41,1
1,10000201402,100002,ALABAMA YOUTH SERVICES,EUFAULA SCHOOL - EUFAULA CAMPUS,CLAYTON,AL,31.882350,-85.256640,7,42,1
2,10000201667,100002,ALABAMA YOUTH SERVICES,CAMPS,MT MEIGS,AL,32.375400,-86.097900,4,41,1
3,10000201670,100002,ALABAMA YOUTH SERVICES,DETENTION CENTER,MT MEIGS,AL,32.375400,-86.097900,4,41,1
4,10000201705,100002,ALABAMA YOUTH SERVICES,WALLACE SCHOOL - MOUNT MEIGS CAMPUS,MOUNT MEIGS,AL,32.368920,-86.081190,8,41,1
...,...,...,...,...,...,...,...,...,...,...,...
34774,199901900777,1999019,SOUTHEAST WEBSTER - GRAND COMM SCHOOL DISTRICT,GRAND ELEMENTARY SCHOOL,BOXHOLM,IA,42.173860,-94.107110,7,43,5
34775,199901901259,1999019,SOUTHEAST WEBSTER - GRAND COMM SCHOOL DISTRICT,IOWA CENTRAL CHARTER HIGH SCHOOL,BURNSIDE,IA,42.348810,-94.106650,7,42,1
34776,199901902075,1999019,SOUTHEAST WEBSTER - GRAND COMM SCHOOL DISTRICT,SOUTHEAST WEBSTER HIGH SCHOOL,BURNSIDE,IA,42.341700,-94.106440,7,42,1
34777,199901902076,1999019,SOUTHEAST WEBSTER - GRAND COMM SCHOOL DISTRICT,SOUTHEAST WEBSTER MIDDLE SCHOOL,BURNSIDE,IA,42.341700,-94.106440,7,42,1
34778,199901902077,1999019,SOUTHEAST WEBSTER - GRAND COMM SCHOOL DISTRICT,DAYTON CENTER,DAYTON,IA,42.260410,-94.069750,7,43,1

In [5]:
len(set(schools_data['school_id']))

34779

In [6]:
list(set(schools_data['school_id']))

[120144003092,
 173732003865,
 120171003936,
 120171003937,
 120171003938,
 69113610297,
 69113610298,
 61111009358,
 120171003997,
 120171003998,
 120039000579,
 120171004009,
 120171004010,
 20024000638,
 120144003214,
 120144003215,
 120144003216,
 120144003217,
 120144003218,
 40674001043,
 120144003219,
 120144003220,
 120144003221,
 192682000542,
 50574000287,
 50574000288,
 170942005407,
 80525000866,
 80525000867,
 80525000868,
 170942005409,
 120039000594,
 173759004844,
 173759004845,
 120039000595,
 160057000112,
 160057000113,
 120039000596,
 60002009279,
 60002009280,
 60002009282,
 60002009283,
 60002009284,
 60002009285,
 60002009286,
 60002009287,
 60002009288,
 60002009289,
 60002009290,
 90282000589,
 90282000590,
 90282000591,
 90282000594,
 90282000595,
 90282000596,
 90282000597,
 50007900385,
 50007900386,
 61494001891,
 61494001892,
 61494001893,
 61494001894,
 61494001895,
 61494001896,
 61494001897,
 61494001898,
 61494001899,
 61494001900,
 61494001901,
 40674001142,
 50261000438,
 40817000706,
 40817000710,
 40817000715,
 40817000719,
 40817000723,
 40817000727,
 180394000663,
 180394000665,
 63132008730,
 40817000731,
 180394000666,
 63186010397,
 120063000862,
 40817000735,
 120063000863,
 180394000667,
 60501000482,
 40817000739,
 60501000483,
 60501000484,
 180394000671,
 40817000743,
 180394000672,
 180394000673,
 180394000674,
 180394000675,
 180394000676,
 180394000677,
 180394000679,
 40817000751,
 180394000680,
 180394000681,
 180394000682,
 193192001861,
 193192001862,
 130330001736,
 171773002066,
 171773002067,
 171773002068,
 171773002069,
 171773002070,
 100002300253,
 130187002217,
 130384003434,
 64098009456,
 120144003449,
 120144003450,
 120144003451,
 120144003452,
 10004201853,
 120144003453,
 120144003454,
 120144003455,
 120144003456,
 120144003457,
 120144003458,
 120144003459,
 181047001473,
 120144003463,
 120144003466,
 61977002379,
 40001601942,
 180394000832,
 171881005511,
 180394000839,
 62827004375,
 62827004376,
 62827004377,
 62827004378,
 62827004379,
 62827004380,
 62827004381,
 62827004382,
 61440000488,
 63213011432,
 63507005929,
 63507005930,
 63507005931,
 62622007789,
 63963005418,
 130330001911,
 61111009785,
 61111009786,
 130357002747,
 191260000762,
 160027000022,
 172739002905,
 160027000023,
 172739002907,
 172739002908,
 40065303069,
 172739002909,
 172739002911,
 192083001885,
 120171004449,
 120171004450,
 180591002147,
 160027000025,
 192083001886,
 192083001887,
 160027000026,
 120144003626,
 120144003627,
 120144003628,
 120144003629,
 120144003630,
 160027000027,
 160027000028,
 160027000030,
 62487003712,
 62487003713,
 62487003714,
 160027000031,
 62487003716,
 160027000032,
 60002009682,
 69102207574,
 62703010391,
 120036000358,
 120036000359,
 120036000360,
 120036000361,
 120036000362,
 120036000363,
 120036000364,
 120036000365,
 120036000366,
 181047001722,
 130330002046,
 40024801923,
 40038302353,
 40817001106,
 50007900818,
 50007900819,
 120090002071,
 120144003738,
 120144003739,
 120144003740,
 120144003741,
 120144003742,
 120144003743,
 120144003744,
 120144003745,
 120144003746,
 120144003747,
 120144003748,
 120198005410,
 120198005411,
 120198005412,
 173222003369,
 130303001260,
 130303001261,
 40817001148,
 40817001149,
 50007900873,
 50007900874,
 40817001177,
 40011301601,
 64214008552,
 10267001577,
 10267001579,
 50717000435,
 50717000436,
 130330002182,
 173597000455,
 192682001168,
 173597000467,
 62649008917,
 172569002778,
 172569002779,
 172569002780,
 172569002781,
 173705003812,
 173705003813,
 120144003882,
 120144003883,
 120144003884,
 120144003885,
 120144003886,
 120144003887,
 60006204231,
 60006204233,
 60006204234,
 60006204235,
 60006204236,
 120090002259,
 60744008537,
 60744008538,
 60744008539,
 60744008540,
 60744008541,
 60744008542,
 60744008543,
 60261008240,
 171371004792,
 171371004794,
 171371004797,
 10267001734,
 10267001735,
 40001602442,
 40001602443,
 120144003994,
 120144003995,
 120144003996,
 120144003999,
 120144004000,
 120144004001,
 120144004002,
 120144004003,
 120144004004,
 120144004005,
 120144004006,
 90255000487,
 90255000488,
 90255000489,
 40817001386,
 90255000490,
 90255000491,
 120144004007,
 120144004008,
 120144004011,
 130187002805,
 40061502390,
 40061502391,
 40061502392,
 40061502393,
 40061502394,
 40061502395,
 80498000822,
 80498000823,
 173759005630,
 51200000961,
 50547000258,
 50547000259,
 51200000962,
 10240000972,
 10240000973,
 10240000975,
 10240000976,
 10240000979,
 10240000980,
 10240000981,
 10240000982,
 10240000983,
 40960000981,
 40960000982,
 40960000983,
 40960000986,
 40960000987,
 40960000988,
 40817001438,
 40960000989,
 40960000990,
 40960000991,
 40960000994,
 40960000995,
 40960000992,
 40960000993,
 61111010274,
 61111010275,
 40061502440,
 40061502441,
 130330002406,
 62460003307,
 90282001389,
 90282001390,
 173454001134,
 180537000942,
 180537000943,
 180537000944,
 171827004403,
 171827004404,
 180537000945,
 180537000946,
 180537000947,
 180537000950,
 180537000952,
 180537000956,
 180537000959,
 180537000960,
 180537000961,
 63140004867,
 40061502468,
 63140004868,
 120144004114,
 120144004115,
 120144004116,
 120144004117,
 180537000995,
 180537000998,
 40061502506,
 40061502507,
 40061502508,
 40061502509,
 40061502510,
 40061502511,
 40061502512,
 40061502513,
 40061502514,
 40061502515,
 40061502516,
 40061502517,
 40061502518,
 40061502519,
 40061502520,
 40061502521,
 60474000441,
 60474000443,
 60474000436,
 60474000445,
 60474000446,
 10240001087,
 60474000447,
 60474000448,
 60474000450,
 64308007001,
 60474000452,
 64308007002,
 10240001094,
 160030000197,
 130330002504,
 180375001677,
 40007500893,
 80525001829,
 120009000039,
 120009000040,
 120009000041,
 120009000042,
 120009000043,
 120009000045,
 120009000046,
 120009000047,
 120009000048,
 120009000049,
 120009000050,
 120009000051,
 120009000052,
 120009000053,
 120009000054,
 120009000055,
 120009000056,
 120009000057,
 120009000058,
 120009000059,
 120009000060,
 120009000061,
 180003800185,
 120009000063,
 61173007488,
 62970004609,
 62970004610,
 120009000064,
 62970004612,
 120009000065,
 120009000067,
 62970004615,
 120009000068,
 62970004618,
 62970004619,
 40817001612,
 40817001613,
 40817001614,
 62970004620,
 62970004622,
 62970004623,
 62970004625,
 130330002580,
 192682001566,
 120117003423,
 120117003424,
 192682001567,
 192682001568,
 130357003427,
 192682001569,
 192682001570,
 130187003046,
 192682001571,
 192682001572,
 192682001573,
 160123000219,
 160123000220,
 172283004092,
 50377000126,
 50377000127,
 130044003524,
 63480005867,
 63480005868,
 63480005869,
 63480005871,
 63480005872,
 63480005873,
 63480005874,
 63480005875,
 63480005877,
 63480005878,
 60207006968,
 60207006969,
 63480005880,
 63480005881,
 63480005882,
 180027000057,
 180027000058,
 180027000059,
 60957000966,
 60957000967,
 60957000968,
 60342011167,
 63186011431,
 120144004394,
 120144004395,
 40477001004,
 40477001005,
 40817001774,
 120144004396,
 120144004397,
 191233000752,
 191233000753,
 191233000754,
 130330002742,
 120117003607,
 90255000920,
 62460003686,
 62460003687,
 62460003688,
 62460003689,
 62460003690,
 62460003691,
 62460003692,
 62460003693,
 62460003694,
 62460003695,
 62460003696,
 160030000493,
 50690000270,
 60744009118,
 60744009119,
 63801001375,
 60015510968,
 120171005390,
 120171005391,
 120171005392,
 120117003730,
 173195003350,
 173195003351,
 40450000353,
 40450000354,
 40450000355,
 40450000357,
 40450000358,
 40450000359,
 63132010000,
 63132010001,
 10240001562,
 50690000417,
 50690000418,
 40960001572,
 160030000690,
 191233001012,
 61146007107,
 120063002181,
 180027000390,
 173678003784,
 62622008914,
 130187003478,
 10213000811,
 10213000812,
 10213000813,
 80471000683,
 80471000684,
 40034502256,
 40034502257,
 40034502258,
 40034502259,
 40034502260,
 40034502261,
 40034502262,
 61440001654,
 61440001655,
 61440001656,
 61440001657,
 61440001658,
 61440001659,
 61440001660,
 61440001661,
 61440001662,
 61440001663,
 61440001664,
 61440001665,
 61440001666,
 61440001668,
 61440001669,
 61440001670,
 61440001671,
 61440001672,
 61440001673,
 61440001674,
 61440001675,
 61440001676,
 61440001677,
 61440001678,
 61440001679,
 61440001680,
 63963006600,
 61440001683,
 61440001684,
 61440001685,
 61440001686,
 61440001687,
 61440001688,
 61440001689,
 61440001690,
 61440001691,
 61440001692,
 90228000410,
 90228000411,
 90228000413,
 90228000414,
 193111000738,
 171371005611,
 40061503148,
 40061503149,
 40061503150,
 40061503151,
 40061503152,
 40061503153,
 171371005612,
 171371005613,
 171371005614,
 171371005615,
 62808000186,
 51173000892,
 51173000893,
 40593000126,
 62808000190,
 160003000001,
 40593000130,
 160003000002,
 61111011016,
 61111011017,
 69100111568,
 180394002128,
 180394002131,
 60261009114,
 130303002346,
 40021001974,
 63132010247,
 40960001804,
 40960001805,
 160030000908,
 40024803089,
 40034502421,
 40450000678,
 120171005736,
 60744009523,
 64214009656,
 40593000276,
 40763000667,
 40763000668,
 62943004533,
 120144004999,
 120144005000,
 120144005001,
 120144005002,
 120117004171,
 120144005005,
 120144005008,
 120144005009,
 120144005010,
 120144005011,
 120144005012,
 120144005013,
 120144005014,
 120144005015,
 120144005016,
 120144005017,
 120144005018,
 120144005019,
 120144005020,
 120144005021,
 120144005022,
 120144005023,
 120144005024,
 120144005025,
 120144005026,
 120144005027,
 120144005028,
 120144005029,
 120144005030,
 120144005031,
 120144005032,
 120144005033,
 120144005034,
 120144005035,
 61111011244,
 120144005036,
 120144005037,
 120144005038,
 120144005039,
 120144005040,
 120144005041,
 120144005042,
 120144005043,
 120144005044,
 120144005045,
 120144005046,
 120144005047,
 120144005048,
 61923002309,
 120090003407,
 40003700712,
 63372003304,
 173338003453,
 173338003454,
 173338003455,
 173338003456,
 192172001296,
 60744009745,
 192172001297,
 40423000083,
 40593000473,
 40593000475,
 40593000477,
 40593000478,
 40593000479,
 170008905761,
 40593000482,
 40423000099,
 40593000483,
 40593000484,
 40593000485,
 40593000487,
 40593000488,
 63132010534,
 172202002467,
 40593000491,
 40593000492,
 60930000940,
 172202002470,
 172202002471,
 40817002549,
 120117004372,
 171549001822,
 192010001180,
 191206000743,
 192010001181,
 172685002870,
 120063002748,
 62433003653,
 170032105608,
 170032105609,
 171549001866,
 172202002568,
 130222000268,
 171549001868,
 171549001869,
 100128000154,
 40593000606,
 40593000610,
 40593000611,
 10213001380,
 40593000612,
 40593000613,
 100128000181,
 50004101312,
 50004101315,
 60207007943,
 69102209235,
 40423000297,
 100128000251,
 180537002239,
 40423000332,
 40906000652,
 40423000334,
 40423000335,
 40423000336,
 174169000219,
 192628001051,
 10186000672,
 10186000673,
 100128000296,
 100128000297,
 60903000367,
 120036002102,
 120036002113,
 62649010506,
 50663000397,
 50663000398,
 173651003763,
 40960002427,
 61111011713,
 61111011714,
 80444000652,
 80444000653,
 61413001616,
 62970005904,
 63132010909,
 180027001256,
 61173008824,
 90201000387,
 90201000388,
 50690001359,
 60011710955,
 171209001459,
 40253000184,
 40253000185,
 40253000186,
 40253000187,
 160003000828,
 160003000829,
 40253000190,
 40253000191,
 40253000192,
 40253000193,
 40253000194,
 120144005634,
 120144005636,
 120144005637,
 120144005638,
 40960002567,
 120144005639,
 120144005641,
 120144005642,
 40253000210,
 40906000915,
 40906000916,
 40906000917,
 50493000214,
 50493000215,
 40906000919,
 40906000920,
 40906000921,
 40906000922,
 40906000923,
 50690001429,
 40906000926,
 40906000927,
 40906000928,
 40906000929,
 40906000930,
 40906000931,
 40906000932,
 40906000933,
 40906000934,
 40906000935,
 40906000936,
 40906000937,
 40906000938,
 40906000939,
 174169000489,
 40906000941,
 40906000942,
 174169000491,
 40906000944,
 40906000945,
 40906000946,
 40906000947,
 50493000243,
 40423000653,
 40423000656,
 40423000660,
 40423000665,
 170005105243,
 170005105244,
 40423000677,
 90228001382,
 40593001080,
 40593001081,
 40593001082,
 40593001083,
 40593001084,
 60420000379,
 60420000380,
 63588010639,
 62916004498,
 120117004954,
 40477002400,
 40593001136,
 60207008446,
 90228001480,
 171692001998,
 171692001999,
 171692002000,
 171692002001,
 171692002002,
 171692002003,
 171692002004,
 170009704503,
 192628001491,
 192628001494,
 193111001815,
 193111001816,
 191050000669,
 193111001817,
 40906001116,
 40906001117,
 191050000670,
 40593001195,
 130222000893,
 40593001218,
 40593001230,
 110004800277,
 40593001239,
 40593001240,
 40450001706,
 190696000306,
 190696000307,
 190696000308,
 130222000951,
 130222000953,
 130222000954,
 130222000955,
 130222000956,
 130222000957,
 60903000903,
 60744010568,
 60744010569,
 60903000904,
 60903000906,
 60903000907,
 60903000908,
 60903000909,
 60903000910,
 60903000911,
 60903000913,
 60903000914,
 60903000915,
 60903000916,
 60903000917,
 60903000918,
 60903000919,
 172175002447,
 172175002449,
 172175002450,
 172175002451,
 191662000991,
 191662000992,
 40593001313,
 50636000110,
 40906001272,
 191179000715,
 191179000716,
 191179000717,
 90174000019,
 170020703123,
 170020703125,
 50663000982,
 170005105565,
 40593001377,
 40593001378,
 180966001578,
 180966001579,
 120036002732,
 62622010302,
 173195004862,
 40593001419,
 40593001421,
 10159000541,
 10159000542,
 10159000544,
 10159000545,
 10159000547,
 10159000548,
 172631002099,
 40593001471,
 61575007240,
 60690009117,
 69104307232,
 40423001127,
 40423001128,
 50636000299,
 120009002030,
 173141003312,
 173141003313,
 120009002034,
 173141003314,
 173141003315,
 120009002037,
 40396000314,
 40396000315,
 40396000316,
 40396000317,
 40396000318,
 40396000319,
 64071011398,
 64071011399,
 40040401993,
 40593001553,
 50636000379,
 50636000380,
 64214011006,
 64214011007,
 40423001231,
 63132011671,
 63132011672,
 61386001564,
 173624003750,
 90174000310,
 90174000311,
 40593001672,
 171638000841,
 174107004112,
 174107004113,
 40423001299,
 40423001300,
 40450002134,
 60744010983,
 60744010984,
 180027002092,
 180027002095,
 170024504564,
 180456000762,
 180456000763,
 180456000764,
 180456000766,
 180456000767,
 180456000769,
 40423001370,
 40423001371,
 10159000860,
 60006206752,
 60006206757,
 120009002280,
 40423001405,
 191206001992,
 120063003983,
 180027002194,
 40423001466,
 40396000649,
 40396000650,
 ...]

In [7]:
location = zip(schools_data['latitude'], schools_data['longitude'])

In [8]:
list(location)

[(33.674696999999995, -86.627775),
 (31.88235, -85.25664),
 (32.3754, -86.0979),
 (32.3754, -86.0979),
 (32.36892, -86.08119),
 (33.582240000000006, -86.71058000000001),
 (34.25999, -86.2076),
 (34.26325, -86.20599),
 (34.27285, -86.21996999999999),
 (34.257529999999996, -86.21859),
 (34.29022, -86.19249),
 (34.53452, -86.25258000000001),
 (34.362770000000005, -86.14224),
 (34.40741, -86.27082),
 (34.175940000000004, -86.32105),
 (34.17686, -86.3203),
 (34.34452, -86.44163),
 (34.53452, -86.25258000000001),
 (34.40031, -86.44615999999999),
 (34.30515, -86.28796),
 (34.30515, -86.28796),
 (34.17667, -86.32324),
 (34.3746, -86.4231),
 (34.37655, -86.42324),
 (34.53452, -86.25258000000001),
 (34.17686, -86.3203),
 (33.34682, -86.84316),
 (33.414359999999995, -86.65997),
 (33.34718, -86.84308),
 (33.3919, -86.7296),
 (33.337720000000004, -86.87653),
 (33.34523, -86.88866999999999),
 (33.38629, -86.72815),
 (33.355340000000005, -86.87063),
 (33.41002, -86.85481),
 (33.397059999999996, -86.80742),
 (33.38742, -86.82954000000001),
 (33.3876, -86.82888),
 (33.4101, -86.76528),
 (33.42807, -86.82429),
 (nan, nan),
 (33.35698, -86.80962),
 (34.707229999999996, -86.71385),
 (34.73965, -86.74104),
 (34.71945, -86.74165),
 (34.69696, -86.75055),
 (34.72185, -86.75039),
 (34.72177, -86.78626),
 (34.75594, -86.73163000000001),
 (34.73188, -86.78182),
 (34.733509999999995, -86.76758000000001),
 (33.433279999999996, -86.0984),
 (33.434670000000004, -86.09045),
 (33.461529999999996, -86.09012),
 (33.42543, -86.11607),
 (30.6875, -88.06415),
 (33.551809999999996, -86.53703),
 (33.55693, -86.55626),
 (33.54929, -86.53739),
 (34.21346, -86.16033),
 (34.2106, -86.16501),
 (34.2063, -86.17603000000001),
 (34.21328, -86.16033),
 (34.20608, -86.17921),
 (33.627629999999996, -86.60537),
 (33.64991, -86.56524),
 (33.64756, -86.56855),
 (33.65652, -86.59523),
 (33.5841, -86.6483),
 (32.1124, -87.0783),
 (33.2082, -87.5374),
 (31.0855, -88.0325),
 (33.5201, -86.81322),
 (33.5286, -86.8075),
 (33.2174, -87.1261),
 (33.2177, -87.5455),
 (34.6576, -87.3049),
 (34.7223, -86.7782),
 (34.5801, -86.4404),
 (34.7433, -86.253),
 (32.3755, -85.6591),
 (34.0747, -85.9352),
 (33.225, -87.1263),
 (34.8012, -86.7208),
 (32.94493, -85.95096),
 (32.938190000000006, -85.95218),
 (32.93543, -85.9306),
 (32.95523, -85.94917),
 (32.93143, -85.97023),
 (31.599, -85.2259),
 (33.3098, -86.7835),
 (33.4812, -86.6647),
 (33.5491, -86.7305),
 (30.7937, -88.2267),
 (33.921, -85.7263),
 (32.3877, -85.2237),
 (30.6217, -88.3397),
 (31.4121, -85.8664),
 (33.3846, -86.0476),
 (32.3598, -86.3088),
 (33.2282, -86.8135),
 (31.2046, -85.384),
 (34.0694, -86.0205),
 (33.5467, -86.758),
 (31.313740000000003, -86.4708),
 (31.3281, -86.4834),
 (31.312, -86.51723),
 (33.66237, -85.81976),
 (33.63273, -85.83345),
 (33.63139, -85.77492),
 (33.665859999999995, -85.85879),
 (33.65719, -85.81044),
 (33.70851, -85.82106),
 (33.66237, -85.81976),
 (33.708459999999995, -85.82108000000001),
 (33.66144, -85.84063),
 (34.32867, -86.49361),
 (34.33298, -86.4965),
 (34.31285, -86.51134),
 (34.32866, -86.48819),
 (34.79081, -86.99556),
 (34.80819, -86.97318),
 (34.804190000000006, -86.95091),
 (34.797129999999996, -86.96914),
 (34.80533, -86.99387),
 (34.79703, -86.96295),
 (34.7843, -86.96417),
 (33.99848, -86.12543000000001),
 (33.99458, -86.11258000000001),
 (34.01703, -86.09781),
 (34.01336, -86.10308),
 (32.59537, -85.46171),
 (32.59854, -85.47601999999999),
 (32.62151, -85.48454),
 (32.60078, -85.46473),
 (32.618970000000004, -85.49311999999999),
 (32.58867, -85.47273),
 (32.58403, -85.46721),
 (32.56285, -85.45744),
 (32.63069, -85.49778),
 (32.547979999999995, -85.55835),
 (32.66069, -86.70173),
 (32.69676, -86.38302),
 (32.452729999999995, -86.4549),
 (32.49607, -86.4746),
 (32.48445, -86.46986),
 (32.45454, -86.4506),
 (32.4633, -86.46902),
 (32.58793, -86.46425),
 (32.45241, -86.42482),
 (32.45763, -86.45479),
 (32.495740000000005, -86.47502),
 (32.433479999999996, -86.66019),
 (32.44805, -86.4283),
 (32.45771, -86.46698),
 (30.888679999999997, -87.77378),
 (30.888679999999997, -87.77378),
 (30.61665, -87.8688),
 (30.26803, -87.68423),
 (30.54038, -87.70787),
 (30.59093, -87.90254),
 (30.419459999999997, -87.59871),
 (30.56718, -87.62448),
 (30.53087, -87.90264),
 (30.40819, -87.68753000000001),
 (31.00208, -87.62279000000001),
 (30.61845, -87.68668000000001),
 (30.543540000000004, -87.75276),
 (30.67391, -87.90557),
 (30.74261, -87.79120999999999),
 (30.48697, -87.69615999999999),
 (30.31575, -87.72893),
 (30.49878, -87.88618000000001),
 (30.590390000000003, -87.73113000000001),
 (30.52089, -87.90574000000001),
 (30.29645, -87.55859),
 (30.676579999999998, -87.8555),
 (30.41433, -87.58686),
 (30.26802, -87.68245999999999),
 (30.41262, -87.74266),
 (30.47232, -87.85715),
 (31.031370000000003, -87.86026),
 (30.86644, -87.78305999999999),
 (30.54891, -87.69637),
 (30.26912, -87.68134),
 (30.50184, -87.90413000000001),
 (30.8656, -87.78315),
 (30.890620000000002, -87.77646999999999),
 (30.612309999999997, -87.90284),
 (30.52378, -87.87858),
 (30.52543, -87.87548000000001),
 (30.40858, -87.69073),
 (30.38549, -87.69211999999999),
 (30.61352, -87.75894),
 (30.8663, -87.7511),
 (30.552709999999998, -87.69861999999999),
 (30.640240000000002, -87.86373),
 (30.78848, -87.84793),
 (30.381240000000002, -87.68706),
 (30.894090000000002, -87.79305),
 (30.8958, -87.7761),
 (30.611109999999996, -87.87272),
 (30.6854, -87.8536),
 (31.880770000000002, -85.44960999999999),
 (31.8652, -85.4331),
 (31.78163, -85.55465),
 (31.45945, -85.60486),
 (31.77747, -85.54895),
 (33.336240000000004, -86.93111999999999),
 (33.40998, -86.9402),
 (33.39128, -86.95205),
 (33.36639, -86.98644),
 (33.37743, -86.95825),
 (33.37814, -86.98001),
 (33.40189, -86.95799),
 (33.366640000000004, -86.98653),
 (33.41295, -86.96058000000001),
 (32.950720000000004, -87.14421),
 (32.94253, -87.16306),
 (32.94271, -87.10494),
 (32.900420000000004, -86.90581),
 (33.11523, -87.11844),
 (33.1228, -87.1281),
 (33.05565, -87.13545),
 (33.11535, -87.12314),
 (32.94587, -87.12499),
 (33.212270000000004, -87.13747),
 (33.52487, -86.77114),
 (33.5034, -86.80493),
 (33.51618, -86.77205),
 (33.571459999999995, -86.70768000000001),
 (33.55937, -86.72849000000001),
 (33.48551, -86.89889000000001),
 (33.50427, -86.89445),
 (33.48791, -86.82974),
 (33.48502, -86.88689000000001),
 (33.58041, -86.69085),
 (33.51265, -86.88539),
 (33.56861, -86.73555),
 (33.4943, -86.81331999999999),
 (33.506440000000005, -86.89432),
 (33.54201, -86.73355),
 (33.5408, -86.76234000000001),
 (33.60546, -86.68583000000001),
 (33.46881, -86.89706),
 (33.53066, -86.77216999999999),
 (33.4939, -86.85181999999999),
 (33.51119, -86.83136999999999),
 (33.54135, -86.75094),
 (33.55567, -86.80461),
 (33.59541, -86.69292),
 (33.6103, -86.68266),
 (33.56324, -86.77960999999999),
 (33.47826, -86.85471),
 (33.46441, -86.88384),
 (33.53706, -86.76841),
 (33.48482, -86.86757),
 (33.544779999999996, -86.82445),
 (33.51889, -86.72776),
 (33.50493, -86.88288),
 (33.55677, -86.81961),
 (33.59109, -86.70666999999999),
 (33.540079999999996, -86.80171999999999),
 (33.53646, -86.73295999999999),
 (33.519220000000004, -86.89171999999999),
 (33.51621, -86.83054),
 (33.46461, -86.8715),
 (33.47961, -86.88071),
 (33.50262, -86.86014),
 (33.52818, -86.71459),
 (33.497890000000005, -86.79685),
 (33.57168, -86.71916),
 (33.61102, -86.69981999999999),
 (33.5246, -86.82902),
 (33.49601, -86.82930999999999),
 (33.4493, -86.88884),
 (33.4495, -86.88832),
 (33.48376, -86.86738000000001),
 (33.531620000000004, -86.77278000000001),
 (33.5221, -86.83429),
 (33.50813, -86.85335),
 (33.54135, -86.75094),
 (33.61826, -86.68131),
 (33.504709999999996, -86.91659),
 (33.50424, -86.8333),
 (33.5646, -86.7747),
 (33.5646, -86.7747),
 (33.547340000000005, -86.74464),
 (33.54135, -86.75094),
 (33.5034, -86.80493),
 (33.521359999999994, -86.88883),
 (33.506440000000005, -86.89432),
 (33.54292, -86.89226),
 (33.59462, -86.7046),
 (33.56138, -86.82324),
 (33.52239, -86.8053),
 (33.5665, -86.7893),
 (33.54538, -86.75842),
 (33.55299, -86.87745),
 (33.53387, -86.80435),
 (33.47622, -86.87103),
 (33.51335, -86.86269),
 (33.5243, -86.88333),
 (33.44157, -86.9191),
 (33.506440000000005, -86.89432),
 (33.50424, -86.8333),
 (33.63609, -86.71215),
 (33.51468, -86.78939),
 (33.51468, -86.78939),
 (nan, nan),
 (33.5665, -86.7893),
 (33.87814, -86.77205),
 (34.03791, -86.42063),
 (34.08592, -86.58615999999999),
 (33.99462, -86.57296),
 (33.883559999999996, -86.77064),
 (33.88705, -86.76656),
 (34.07168, -86.587),
 (33.908570000000005, -86.61723),
 (33.78738, -86.621),
 (34.07751, -86.46466),
 (33.90548, -86.51249),
 (33.99292, -86.56896),
 (33.99149, -86.55453),
 (33.90726, -86.61716),
 (33.99609, -86.58144),
 (34.07751, -86.46466),
 (31.11915, -87.06866),
 (31.125740000000004, -87.06283),
 (31.13738, -87.06866),
 (32.13158, -85.72436),
 (32.0753, -85.4718),
 (32.13242, -85.71949000000001),
 (32.146190000000004, -85.71202),
 (32.143440000000005, -85.7133),
 (31.64195, -86.74155999999999),
 (31.83039, -86.65231),
 (31.83758, -86.62683),
 (31.54536, -86.71441999999999),
 (31.645459999999996, -86.72831),
 (31.833859999999998, -86.62576),
 (31.8315, -86.6395),
 (31.83222, -86.6264),
 (33.7061, -85.82169),
 (33.77602, -85.8864),
 (nan, nan),
 (33.78583, -86.00336),
 (33.70174, -85.8308),
 (33.70176, -85.83766999999999),
 (33.70173, -85.83059),
 (33.754, -85.81576),
 (33.74695, -85.83495),
 (33.65268, -85.87954),
 (33.74778, -85.68760999999999),
 (33.69634, -85.82372),
 (33.80092, -85.76004),
 (33.788129999999995, -86.00276),
 (33.884609999999995, -85.81097),
 (33.72218, -85.67411),
 (33.88541, -85.8148),
 (33.64754, -85.87876999999999),
 (33.775729999999996, -85.88208),
 (32.89795, -85.39579),
 (32.79345, -85.18605),
 (33.01396, -85.33969),
 (32.83495, -85.22936999999999),
 (32.899429999999995, -85.39855),
 (32.81345, -85.17125),
 (32.83893, -85.18316999999999),
 (32.89087, -85.3985),
 (32.80178, -85.18145),
 (32.80616, -85.19693000000001),
 (32.9081, -85.4265),
 (34.22002, -85.60542),
 (34.15033, -85.67345),
 (34.15167, -85.6778),
 (34.16454, -85.65916),
 (34.2707, -85.5617),
 (34.239940000000004, -85.76783),
 (33.9727, -85.5538),
 (34.15899, -85.68754),
 (32.82844, -86.7856),
 (32.96547, -86.74748000000001),
 (32.80853, -86.88041),
 (32.914590000000004, -86.71646),
 (32.824020000000004, -86.6155),
 (32.825379999999996, -86.61561999999999),
 (32.74942, -86.50889000000001),
 (32.96454, -86.74707),
 (32.8335, -86.6725),
 (32.8254, -86.61584),
 (32.8218, -86.61443),
 (32.98129, -86.72916),
 (31.850379999999998, -88.31562),
 (32.088640000000005, -88.21645),
 (31.76809, -88.32803),
 (32.087720000000004, -88.23236),
 (32.079809999999995, -88.23293000000001),
 (31.71043, -87.77504),
 (31.794, -88.0679),
 (31.794, -88.0679),
 (31.71329, -87.79835),
 (31.5126, -87.89405),
 (31.53057, -87.89532),
 (31.70213, -87.76454),
 (31.53101, -87.89737),
 (31.548779999999997, -87.8812),
 (33.271809999999995, -85.8394),
 (33.27179, -85.83906999999999),
 (33.31073, -85.75263000000001),
 (33.31064, -85.75820999999999),
 (33.64736, -85.57096999999999),
 (33.64826, -85.57096999999999),
 (33.732, -85.43607),
 (33.52405, -85.63682),
 (33.52313, -85.34555999999999),
 (33.59845, -85.48276),
 (nan, nan),
 (33.523990000000005, -85.3483),
 (31.220879999999998, -86.1716),
 (31.56614, -86.01144000000001),
 (31.38271, -85.93471),
 (nan, nan),
 (31.39433, -85.92092),
 (34.77086, -87.9623),
 (34.753029999999995, -87.9587),
 (34.765640000000005, -87.9639),
 (34.6949, -87.52883),
 (34.671009999999995, -87.70053),
 (34.75593, -87.48501999999999),
 (34.69876, -87.53758),
 (34.64378, -87.77989000000001),
 (34.66013, -87.70223),
 (31.3264, -87.0248),
 (31.42827, -86.96843),
 (31.4558, -86.9448),
 (31.4218, -86.95053),
 (31.4208, -87.1804),
 (31.43427, -86.94048000000001),
 (32.8655, -86.2691),
 (32.8655, -86.2691),
 (32.9036, -86.2129),
 (32.8928, -86.1552),
 (31.00455, -86.32666),
 (31.39855, -86.4425),
 (31.3574, -86.2032),
 (31.0054, -86.3295),
 (31.3032, -86.4928),
 (31.4464, -86.6124),
 (31.39855, -86.4425),
 (31.01615, -86.35821),
 (nan, nan),
 (31.59415, -86.2554),
 (31.952820000000003, -86.31379),
 (31.71459, -86.27459),
 (31.705609999999997, -86.26826),
 (34.18849, -86.83783000000001),
 (34.184329999999996, -86.84562),
 (34.18801, -86.84236),
 (34.173629999999996, -86.83665),
 (34.17796, -86.85674),
 (34.184329999999996, -86.84562),
 (34.1782, -86.84154000000001),
 (34.26698, -86.60956999999999),
 (33.98216, -87.0323),
 (33.98199, -87.03224),
 (34.25414, -86.68783),
 (34.01332, -86.75163),
 (34.10232, -86.88003),
 (34.06162, -86.76007),
 (34.17569, -86.61847),
 (34.20752, -87.05299000000001),
 (34.14208, -87.00648000000001),
 (34.24289, -86.86479),
 (34.141709999999996, -86.74141999999999),
 (34.23598, -86.96428),
 (34.25414, -86.68783),
 (34.25414, -86.68783),
 (34.10232, -86.88003),
 (34.10232, -86.8801),
 (34.06162, -86.76007),
 (34.06162, -86.76007),
 (34.17569, -86.61847),
 (34.24289, -86.86479),
 (34.24289, -86.86479),
 (34.23598, -86.96428),
 (34.235820000000004, -86.96523),
 (34.2227, -86.85905),
 (34.09765, -86.88788000000001),
 (34.222229999999996, -86.85899),
 (34.17252, -86.84642),
 (nan, nan),
 (nan, nan),
 (31.5559, -85.5715),
 (31.600440000000003, -85.7323),
 (31.3445, -85.4977),
 (31.5658, -85.5446),
 (31.3445, -85.4977),
 (31.3283, -85.59591),
 (31.3113, -85.553),
 (31.31447, -85.71138),
 (31.31447, -85.71138),
 (31.31447, -85.71138),
 (31.31447, -85.71138),
 (32.4233, -86.9614),
 (32.661359999999995, -86.92888),
 (32.24285, -87.22936),
 (32.65283, -86.92588),
 (32.2963, -87.2237),
 (32.34669, -87.25693000000001),
 (32.2885, -87.0079),
 (32.32138, -86.90254),
 (32.36435, -86.98345),
 (32.37146, -87.01548000000001),
 (32.49732, -86.98259),
 (32.49877, -86.98326),
 (32.37158, -87.01550999999999),
 (32.3528, -86.9847),
 (34.2527, -85.8685),
 (34.28833, -85.99481),
 (34.45535, -85.90408000000001),
 (34.407959999999996, -86.03543),
 (34.635220000000004, -85.76915),
 (34.71114, -85.67548000000001),
 (34.5638, -85.571),
 (34.483, -85.82136),
 (34.37415, -85.77541),
 (34.56335, -85.81411999999999),
 (34.56351, -85.61535),
 (34.48718, -85.82995),
 (34.48718, -85.82995),
 (34.48718, -85.82995),
 (34.3416, -86.0215),
 (34.559, -87.01839),
 (34.58112, -87.00359),
 (34.567409999999995, -86.99431),
 (34.58696, -86.9948),
 (34.59553, -86.97514),
 (34.57837, -86.9461),
 (34.5267, -86.9714),
 (34.5982, -86.9719),
 (34.58885, -86.96731),
 (34.594159999999995, -86.97251),
 (34.59774, -86.99691),
 (34.57738, -86.96219),
 (34.60935, -87.00613),
 (34.58436, -87.0128),
 (34.54545, -86.99471),
 (34.607890000000005, -86.97505),
 (34.57544, -87.0382),
 (34.5487, -87.01159),
 (34.60772, -86.97674),
 (32.4982, -87.84628000000001),
 (32.51005, -87.83515),
 (32.512240000000006, -87.82986),
 (32.5045, -87.8579),
 (31.23507, -85.37469),
 (31.19613, -85.39133000000001),
 (31.208540000000003, -85.39331),
 (31.241220000000002, -85.42163000000001),
 (31.23902, -85.41958000000001),
 (31.21153, -85.37626999999999),
 (31.219209999999997, -85.42824),
 (31.236279999999997, -85.40256),
 (31.210079999999998, -85.41362),
 (31.233959999999996, -85.37259),
 (31.24257, -85.38982),
 (31.26577, -85.38071),
 (31.19299, -85.35121),
 (31.22035, -85.48597),
 (31.27148, -85.39565999999999),
 (31.19378, -85.35378),
 (31.2049, -85.435),
 (31.2664, -85.38022),
 (31.23057, -85.40404000000001),
 (31.27726, -85.46299),
 (31.42265, -86.10495),
 (31.42489, -86.10405),
 (31.42489, -86.10405),
 (32.54661, -86.2128),
 (32.63394, -86.02993000000001),
 (32.6362, -86.324),
 (32.5115, -86.3757),
 (32.49283, -86.36561999999999),
 (32.54659, -86.20685),
 (32.55017, -86.22058),
 (32.50582, -86.3497),
 (32.54936, -86.21587),
 (32.63524, -86.02335),
 (32.63147, -86.32488000000001),
 (32.49984, -86.35828000000001),
 (32.63005, -86.02936),
 (32.636520000000004, -86.32686),
 (32.543409999999994, -86.21069),
 (31.31045, -85.86049),
 (31.306829999999998, -85.83783000000001),
 (31.37122, -85.84637),
 (31.324509999999997, -85.85427),
 (31.312079999999998, -85.85784),
 (31.32409, -85.85334),
 (31.33863, -85.84494000000001),
 (31.30498, -85.83833),
 (31.32637, -85.81928),
 (31.332420000000003, -85.81215999999999),
 (31.01373, -87.48624000000001),
 (31.006859999999996, -87.48753),
 (31.044729999999998, -87.49351999999999),
 (31.039920000000002, -87.17491),
 (31.22, -87.4619),
 (31.060640000000003, -87.16983),
 (31.09157, -87.05566),
 (31.03995, -87.17491),
 (31.11673, -87.09817),
 (31.0073, -87.2734),
 (31.004490000000004, -87.2688),
 (31.08575, -87.06465),
 (31.08575, -87.06466999999999),
 (31.017409999999998, -87.50417),
 (34.12214, -86.11838),
 (34.14264, -86.00143),
 (34.066720000000004, -85.92773000000001),
 (33.9571, -85.93307),
 (33.96673, -85.93444000000001),
 (33.99691, -85.86927),
 (33.996990000000004, -85.86832),
 (34.035759999999996, -86.12463000000001),
 (33.94601, -86.05922),
 (34.078720000000004, -85.98921),
 (34.17711, -86.12427),
 (33.9225, -86.02242),
 (34.06337, -86.30281),
 (34.03051, -86.26252),
 (34.166290000000004, -86.07157),
 (33.95775, -86.04349),
 (33.99736, -86.1042),
 (33.99742, -86.10441999999999),
 (33.966770000000004, -85.93444000000001),
 (33.94619, -86.06189),
 (33.91551, -86.02205),
 (34.01709, -85.87116),
 (34.024640000000005, -85.99540999999999),
 (31.868309999999997, -85.15149),
 (31.91702, -85.13928),
 (31.915059999999997, -85.14126999999999),
 (31.8836, -85.16238),
 (31.897409999999997, -85.15069),
 (31.89736, -85.15068000000001),
 (33.490590000000005, -86.90630999999999),
 (33.49005, -86.9078),
 (33.46758, -86.9182),
 (33.45975, -86.92701),
 (33.47732, -86.91315),
 (33.47391, -86.91219),
 (33.49005, -86.9078),
 (33.660059999999994, -87.59979),
 (33.68755, -87.82725),
 (33.83061, -87.74363000000001),
 (33.66445, -87.60099),
 (33.68679, -87.82692),
 (33.6889, -87.8264),
 (34.83374, -87.66178000000001),
 (34.8092, -87.67322),
 (34.849070000000005, -87.67653),
 (34.83019, -87.68301),
 (34.8246, -87.6591),
 (34.8092, -87.67322),
 (34.79607, -87.68285999999999),
 (34.79772, -87.69054),
 (34.82074, -87.69411),
 (34.48633, -85.67535),
 (34.45562, -85.70657),
 (34.482490000000006, -85.68138),
 (34.48956, -85.66637),
 (34.4743, -87.86583),
 (34.38194, -87.59878),
 (34.3502, -87.7082),
 (34.4346, -88.1376),
 (34.525, -87.62111),
 (34.373979999999996, -88.05936),
 (34.46, -87.854),
 (34.3501, -87.7073),
 (33.999629999999996, -85.98353),
 (34.00111, -85.9709),
 (34.006679999999996, -86.01172),
 (34.023709999999994, -86.03649),
 (33.97376, -86.02218),
 (34.01422, -86.02071),
 (34.02431, -86.0332),
 (34.00281, -85.96505),
 (34.03933, -86.02026),
 (34.00893, -86.00868),
 (34.01121, -86.05471),
 (34.00479, -85.98866),
 (34.00105, -85.96635),
 (34.02613, -86.03437),
 (34.00105, -85.96635),
 (34.00111, -85.96862),
 (34.00111, -85.96823),
 (34.03949, -85.97051),
 (nan, nan),
 (31.042340000000003, -85.87924),
 (31.04908, -85.88539),
 (31.04222, -85.87921),
 (31.0966, -85.69924),
 (31.11907, -86.04896),
 (31.099829999999997, -85.60235),
 (31.12518, -86.04334),
 (31.11907, -86.04896),
 (31.09858, -85.70116),
 (31.0966, -85.69924),
 (31.1078, -85.5978),
 (31.099829999999997, -85.60235),
 (32.84564, -87.89724),
 (32.7646, -88.0303),
 (32.928, -87.9743),
 (32.8383, -87.8944),
 (32.8332, -87.87496),
 (34.36159, -86.30598),
 (34.321259999999995, -86.33227),
 (34.35497, -86.30748),
 (34.320479999999996, -86.3122),
 (32.70726, -87.58785999999999),
 (32.70304, -87.6019),
 (32.9599, -87.598),
 (33.000040000000006, -87.63214),
 (32.565540000000006, -87.58001),
 (32.721, -87.5929),
 (33.25659, -87.60338),
 (32.70304, -87.60045),
 (32.8758, -87.73465999999999),
 (32.8591, -87.7154),
 (34.22607, -87.60634),
 (34.22606, -87.60628),
 (34.22634, -87.60634),
 (34.42272, -86.94558),
 (34.43923, -86.94689),
 (34.45626, -86.92319),
 (34.432759999999995, -86.93271),
 (34.43329, -86.93244),
 (34.43329, -86.93244),
 (31.5803, -85.2715),
 (31.5992, -85.2264),
 (31.56713, -85.24893),
 (31.35022, -85.33829),
 (31.3492, -85.3408),

In [26]:
schools_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34779 entries, 0 to 34778
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   school_id              34779 non-null  int64
 1   agency_id              34779 non-null  int64
 2   operating_agency_name  34224 non-null  object
 3   school_name            34779 non-null  object
 4   city_name              34778 non-null  object
 5   state                  34779 non-null  object
 6   latitude               33279 non-null  float64
 7   longitude              33279 non-null  float64
 8   metro_centric_locale   34779 non-null  object
 9   urban_centric_locale   34779 non-null  object
 10  school_status_code     34779 non-null  int64
dtypes: float64(2), int64(3), object(6)
memory usage: 2.9+ MB

In [27]:
schools_data.describe()

,school_id,agency_id,latitude,longitude,school_status_code
count,3.477900e+04,3.477900e+04,33279.000000,33279.000000,34779.000000
mean,1.018973e+11,1.018973e+06,36.567146,-100.335991,1.255413
std,5.328345e+10,5.328345e+05,5.622711,18.081534,1.101551
min,1.000020e+10,1.000020e+05,19.065040,-176.647800,1.000000
25%,6.151801e+10,6.151800e+05,33.524650,-117.879770,1.000000
50%,9.011700e+10,9.011700e+05,36.713100,-92.280750,1.000000
75%,1.600510e+11,1.600510e+06,40.381755,-85.828530,1.000000
max,1.999019e+11,1.999019e+06,71.291790,-71.804240,8.000000

In [42]:
schools_data['school_status_code'].isnull().values.any()

False

In [ ]:
schools_data.columns = ['school_id', 'agency_id', 'operating_agency_name', 'school_name', 'city_name', 'state', 'latitude', 'longitude', 'metro_centric_locale', 'urban_centric_locale', 'school_status_code']

In [12]:
schools_data['longitude'].isnull().values.any()

True

In [10]:
schools_data['latitude'].isnull().count_values()

True

In [13]:
schools_data['longitude'].isnull().sum()

1500

In [14]:
schools_data['latitude'].isnull().sum()

1500

In [22]:
schools_data_with_na = schools_data[schools_data.latitude.isnull()]

In [23]:
schools_data_with_na

,school_id,agency_id,operating_agency_name,school_name,city_name,state,latitude,longitude,metro_centric_locale,urban_centric_locale,school_status_code
40,10000701825,100007,HOOVER CITY,TRACE CROSSINGS MIDDLE SCHOOL,HOOVER,AL,NaN,NaN,2,N,7
309,10039001823,100390,BIRMINGHAM CITY,OSSIE WARE MITCHELL ELEMENTARY SCHOOL,BIRMINGHAM,AL,NaN,NaN,1,N,7
345,10054000239,100540,CALHOUN COUNTY,DE ARMANVILLE JR HIGH SCHOOL,ANNISTON,AL,NaN,NaN,N,N,2
417,10078001671,100780,CLEBURNE COUNTY,CLEBURNE COUNTY MIDDLE SCHOOL,HEFLIN,AL,NaN,NaN,7,N,7
422,10081001565,100810,COFFEE COUNTY,PATHWAY SCHOOL,NEW BROCKTON,AL,NaN,NaN,N,N,2
...,...,...,...,...,...,...,...,...,...,...,...
34514,192682001168,1926820,SOUTHEAST POLK COMM SCHOOL DISTRICT,CLAY ELEMENTARY SCHOOL,ALTTONA,IA,NaN,NaN,4,N,7
34528,192691001578,1926910,SPENCER COMM SCHOOL DISTRICT,JEFFERSON ELEMENTARY SCHOOL,SPENCER,IA,NaN,NaN,N,N,2
34586,192868001413,1928680,URBANDALE COMM SCHOOL DISTRICT,WEBSTER ELEMENTARY SCHOOL,URBANDALE,IA,NaN,NaN,4,N,7
34598,192898001429,1928980,VAN BUREN COMM SCHOOL DISTRICT,MILTON PRESCHOOL,MILTON,IA,NaN,NaN,7,N,7
34649,193048001727,1930480,WATERLOO COMM SCHOOL DISTRICT,KINGSLEY ELEMENTARY SCHOOL,WATERLOO,IA,NaN,NaN,N,N,2

In [24]:
schools_data_with_na_long = schools_data[schools_data.longitude.isnull()]

In [25]:
schools_data_with_na_long

,school_id,agency_id,operating_agency_name,school_name,city_name,state,latitude,longitude,metro_centric_locale,urban_centric_locale,school_status_code
40,10000701825,100007,HOOVER CITY,TRACE CROSSINGS MIDDLE SCHOOL,HOOVER,AL,NaN,NaN,2,N,7
309,10039001823,100390,BIRMINGHAM CITY,OSSIE WARE MITCHELL ELEMENTARY SCHOOL,BIRMINGHAM,AL,NaN,NaN,1,N,7
345,10054000239,100540,CALHOUN COUNTY,DE ARMANVILLE JR HIGH SCHOOL,ANNISTON,AL,NaN,NaN,N,N,2
417,10078001671,100780,CLEBURNE COUNTY,CLEBURNE COUNTY MIDDLE SCHOOL,HEFLIN,AL,NaN,NaN,7,N,7
422,10081001565,100810,COFFEE COUNTY,PATHWAY SCHOOL,NEW BROCKTON,AL,NaN,NaN,N,N,2
...,...,...,...,...,...,...,...,...,...,...,...
34514,192682001168,1926820,SOUTHEAST POLK COMM SCHOOL DISTRICT,CLAY ELEMENTARY SCHOOL,ALTTONA,IA,NaN,NaN,4,N,7
34528,192691001578,1926910,SPENCER COMM SCHOOL DISTRICT,JEFFERSON ELEMENTARY SCHOOL,SPENCER,IA,NaN,NaN,N,N,2
34586,192868001413,1928680,URBANDALE COMM SCHOOL DISTRICT,WEBSTER ELEMENTARY SCHOOL,URBANDALE,IA,NaN,NaN,4,N,7
34598,192898001429,1928980,VAN BUREN COMM SCHOOL DISTRICT,MILTON PRESCHOOL,MILTON,IA,NaN,NaN,7,N,7
34649,193048001727,1930480,WATERLOO COMM SCHOOL DISTRICT,KINGSLEY ELEMENTARY SCHOOL,WATERLOO,IA,NaN,NaN,N,N,2